### ISSUE TITLE
react/jsx-closing-bracket-location line-aligned forces floating >

### ISSUE THREAD

**Issue by garth** [feross/eslint-config-standard-jsx#1]
This change is a little too opinionated and forces some ugly looking code (less readable) with floating > whenever the opening jsx command is multi-line.

before you could do:

``` js
<div style={{
  color: 'red'
}}>
  content
</div>
```

But now you are always forced to add an empty line with a floating >

``` js
<div style={{
  color: 'red'
}}
>
  content
</div>
```

IMO the first example is much cleaner.

**Comment by feross** [comment]
Agree. Fixed in 1.1.1 and standard 6.0.4.
