### ISSUE TITLE
Double quotes are enforced

### ISSUE THREAD

**Issue by TimonVS** [feross/eslint-config-standard-jsx#10]
It seems like the `jsx-quotes` rule was set to enforce double quotes (https://github.com/feross/eslint-config-standard-jsx/commit/f85f775f6e79dce64f635708ae8e364808b2aa5d).

Shouldn't we be using single quotes? I interpret JSX as JS so I'd use single quotes there too.

**Comment by feross** [comment]
This was discussed in https://github.com/feross/eslint-config-standard/issues/27 a little while ago.  You can take a look at the discussion there and see that we decided to go with double quotes. But standard v8 is still in beta until September 1, 2016 so this might change.

Apologies for not marking the change as beta on this repo as well.

**Comment by Nicolab** [comment]
Seemingly, the [single quotes were chosen](https://github.com/feross/eslint-config-standard-jsx/blob/master/eslintrc.json#L14) in eslint-config-standard-jsx :(
Against the direction of jsx-quotes (double), [React dev](https://github.com/facebook/react/blob/master/.eslintrc.js#L31) (double), majority of the React users (double) and the docs in the Web (double), ...

The JSX is written like XML / HTML, not like JS. The single quote rule for the JSX, it's not productive :(

**Comment by dcousens** [comment]
@Nicolab this was no small decision.
https://github.com/feross/standard/issues/564#issuecomment-240631820

**Comment by Nicolab** [comment]
I imagine, in this case the easiest way is the more appropriate.
This rule will cause trouble for beginners and majority of users (have to switch between the same conventions of JSX / XML / HTML and this convention).

Now that is done, I override this strange rule and it's no use that I argue more around the single quotes in JSX :)

---

_Sorry for my bad english_
