### ISSUE TITLE
InfernoJS Support

### ISSUE THREAD

**Issue by aaronclong** [feross/eslint-config-standard-jsx#18]
Marks the import of [InfernoJS](https://github.com/infernojs/inferno) as an unused import, causing problems with rendering.

**Comment by feross** [comment]
You need to tell the linter to treat your JSX variable as used. Try adding this at the top of each file that uses Inferno.

```js
/** @jsx Inferno */
```

By default it's set to:

```js
/** @jsx React.createElement **/
```

**Comment by aaronclong** [comment]
Is there anyway to modify this to a config file so that it is less of an eyesoar?

It is trivial to repeat that comment, but I rather not do it for every file, especially in a larger project.

**Comment by feross** [comment]
If you're using eslint-config-standard-jsx directly, then you can add a "settings" key to your configuration. See https://github.com/yannickcr/eslint-plugin-react#configuration

If you're using the `standard` CLI, then right now, there's no way to put it in the `"standard"` field of `package.json`, but that's a good idea. If you want, you can propose it as a feature over on that issue tracker :) https://github.com/feross/standard
