### ISSUE TITLE
Outdated eslint version in peerDependencies

### ISSUE THREAD

**Issue by unindented** [feross/eslint-config-standard-jsx#2]
`peerDependencies` in `package.json` require outdated `eslint@2.0.0-rc.0`: https://github.com/feross/eslint-config-standard-jsx/blob/e3ce2b04595540d3e74c934f6f9bae6ac9810ab9/package.json#L14

**Comment by unindented** [comment]
Ugh, I didn't see the `^`. Forget this.

**Comment by feross** [comment]
I just bumped the dependency to make it clearer. :)

**Comment by unindented** [comment]
👍😊
